FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS build
WORKDIR /src
COPY ["CrudAspCore.csproj", "./"]
RUN dotnet restore "./CrudAspCore.csproj"
COPY . .
RUN dotnet build "CrudAspCore.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "CrudAspCore.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "CrudAspCore.dll"]
